# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

   config.vm.define :jenkins do |jenkins|
      jenkins.vm.box = "ubuntu/trusty64"  
	  jenkins.vm.network "private_network", ip: "192.168.33.65"
	  jenkins.vm.provider "virtualbox" do |vb|
	     vb.memory = 2048
	     vb.name = "jenkins"
      end	  
      jenkins.vm.provision "shell" do |s|
          s.path = "scripts/bootjenkins.sh"
      end
   end
   
end