# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

   config.vm.define :jenkinsdocker do |jenkinsdocker|
      jenkinsdocker.vm.box = "ubuntu/trusty64"  
	  jenkinsdocker.vm.network "private_network", ip: "192.168.33.66"
	  jenkinsdocker.vm.provider "virtualbox" do |vb|
	     vb.memory = 2048
	     vb.name = "jenkinsdocker"
      end	  
      jenkinsdocker.vm.provision "shell" do |s|
          s.path = "scripts/bootjenkinsdocker.sh"
      end
   end
   
end